### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by WangHelin1997** [edufonseca/FSD50K_baseline#1]
Dear authors,

Wonderful work! Would you please release a system implemented in **Pytorch**?

Thanks a lot.

**Comment by edufonseca** [comment]
Thanks for the interest! Indeed, releasing Pytorch code would be great. And it may happen in the future, but not in the near one as we are currently very busy (I just started an internship). First, we still have to release a TF framework. 

Thanks for bringing that up!

**Comment by djensenius** [comment]
Hi @edufonseca - do you have a timeline for the TF framework?

AWESOME work. Excited to dig in.

**Comment by edufonseca** [comment]
At the moment it is difficult to say. I've been super busy lately, and I have a couple of things to work on before getting to the code. BTW, one of them is writing a blogpost about the FSD50K dataset. 

As I said, I'm now interning in a company, so cleaning the code is something I would do in my spare time. I'd like to think that November would be the month (but I can't guarantee it)

please be patient! thanks!

**Comment by SarthakYadav** [comment]
@WangHelin1997 

> Dear authors,
> 
> Wonderful work! Would you please release a system implemented in **Pytorch**?
> 
> Thanks a lot.

I've implemented a PyTorch version [here](https://github.com/SarthakYadav/fsd50k-pytorch), using [pytorch-lightning](https://github.com/PyTorchLightning/pytorch-lightning). Pre-trained models trained with SpecAugment and Background Noise injection augmentation are available.

**Comment by edufonseca** [comment]
That's great news! Thanks Sarthak.

Closing the issue then.

Sorry for the delay in releasing the TF framework. Been very busy. Will happen at the beginning of March as I am coming back to the university again and this task is at the top of my list.
